### ISSUE TITLE
Stape Logging standart

### ISSUE THREAD

**Issue by Bukashk0zzz** [PiwikPRO/server-side-template-for-gtm-v2#5]
It will be great if tag will support Stape Logging Standard.
Currently it supported by majority of sGTM tags.

https://github.com/stape-io/gtm-standards/blob/main/standards/GTMS-3.md

If it's good for you I can prepare PR.

**Comment by abartczakpiwik** [comment]
Hi @Bukashk0zzz!

That would be a good addition. Feel free to draft/prepare a PR.

**Comment by abartczakpiwik** [comment]
Thanks for the contribution @Bukashk0zzz :).
